// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: push/push.proto

package pb_push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdPushKind int32

const (
	CmdPushKind_Cmd_UNKNOW CmdPushKind = 0
	CmdPushKind_Cmd_Chat   CmdPushKind = 1 // 聊天
)

// Enum value maps for CmdPushKind.
var (
	CmdPushKind_name = map[int32]string{
		0: "Cmd_UNKNOW",
		1: "Cmd_Chat",
	}
	CmdPushKind_value = map[string]int32{
		"Cmd_UNKNOW": 0,
		"Cmd_Chat":   1,
	}
)

func (x CmdPushKind) Enum() *CmdPushKind {
	p := new(CmdPushKind)
	*p = x
	return p
}

func (x CmdPushKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdPushKind) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[0].Descriptor()
}

func (CmdPushKind) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[0]
}

func (x CmdPushKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdPushKind.Descriptor instead.
func (CmdPushKind) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

type PushChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushChat) Reset() {
	*x = PushChat{}
	mi := &file_push_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushChat) ProtoMessage() {}

func (x *PushChat) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushChat.ProtoReflect.Descriptor instead.
func (*PushChat) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushChat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_push_push_proto protoreflect.FileDescriptor

const file_push_push_proto_rawDesc = "" +
	"\n" +
	"\x0fpush/push.proto\x12\x04push\"$\n" +
	"\bPushChat\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent*+\n" +
	"\vCmdPushKind\x12\x0e\n" +
	"\n" +
	"Cmd_UNKNOW\x10\x00\x12\f\n" +
	"\bCmd_Chat\x10\x01B)Z'github.com/k8s/muyi/api/pb/push;pb_pushb\x06proto3"

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData []byte
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)))
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_push_push_proto_goTypes = []any{
	(CmdPushKind)(0), // 0: push.CmdPushKind
	(*PushChat)(nil), // 1: push.PushChat
}
var file_push_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		EnumInfos:         file_push_push_proto_enumTypes,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
