[push]
    port="4100" # 当前服务的端口号，k8s 中同一种服务这些端口号一样
    logPath = "runtime/logs/k8s-push.log"      #日志文件路径
    errLogPath = "runtime/logs/k8s-push.log.err" # error 日志路径 可以不太填写 默认在filename后加.err
    serviceNameKey = "push-service" # 服务的名字, 每种服务不一样 每个相同服务不同实例一样
