// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: room/room.proto

package pb_room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务小类接口
type CmdRoomKind int32

const (
	CmdRoomKind_Cmd_ROOM_UNKNOW CmdRoomKind = 0
	CmdRoomKind_CMD_ROOM_CREATE CmdRoomKind = 1 // 创建房间
)

// Enum value maps for CmdRoomKind.
var (
	CmdRoomKind_name = map[int32]string{
		0: "Cmd_ROOM_UNKNOW",
		1: "CMD_ROOM_CREATE",
	}
	CmdRoomKind_value = map[string]int32{
		"Cmd_ROOM_UNKNOW": 0,
		"CMD_ROOM_CREATE": 1,
	}
)

func (x CmdRoomKind) Enum() *CmdRoomKind {
	p := new(CmdRoomKind)
	*p = x
	return p
}

func (x CmdRoomKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdRoomKind) Descriptor() protoreflect.EnumDescriptor {
	return file_room_room_proto_enumTypes[0].Descriptor()
}

func (CmdRoomKind) Type() protoreflect.EnumType {
	return &file_room_room_proto_enumTypes[0]
}

func (x CmdRoomKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdRoomKind.Descriptor instead.
func (CmdRoomKind) EnumDescriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

type RoomCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateReq) Reset() {
	*x = RoomCreateReq{}
	mi := &file_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateReq) ProtoMessage() {}

func (x *RoomCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateReq.ProtoReflect.Descriptor instead.
func (*RoomCreateReq) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCreateReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateResp) Reset() {
	*x = RoomCreateResp{}
	mi := &file_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateResp) ProtoMessage() {}

func (x *RoomCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateResp.ProtoReflect.Descriptor instead.
func (*RoomCreateResp) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomCreateResp) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

var File_room_room_proto protoreflect.FileDescriptor

const file_room_room_proto_rawDesc = "" +
	"\n" +
	"\x0froom/room.proto\x12\x04base\"'\n" +
	"\rRoomCreateReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\"(\n" +
	"\x0eRoomCreateResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId*7\n" +
	"\vCmdRoomKind\x12\x13\n" +
	"\x0fCmd_ROOM_UNKNOW\x10\x00\x12\x13\n" +
	"\x0fCMD_ROOM_CREATE\x10\x01B)Z'github.com/k8s/muyi/api/pb/room;pb_roomb\x06proto3"

var (
	file_room_room_proto_rawDescOnce sync.Once
	file_room_room_proto_rawDescData []byte
)

func file_room_room_proto_rawDescGZIP() []byte {
	file_room_room_proto_rawDescOnce.Do(func() {
		file_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)))
	})
	return file_room_room_proto_rawDescData
}

var file_room_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_room_room_proto_goTypes = []any{
	(CmdRoomKind)(0),       // 0: base.CmdRoomKind
	(*RoomCreateReq)(nil),  // 1: base.RoomCreateReq
	(*RoomCreateResp)(nil), // 2: base.RoomCreateResp
}
var file_room_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_room_proto_init() }
func file_room_room_proto_init() {
	if File_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_room_proto_goTypes,
		DependencyIndexes: file_room_room_proto_depIdxs,
		EnumInfos:         file_room_room_proto_enumTypes,
		MessageInfos:      file_room_room_proto_msgTypes,
	}.Build()
	File_room_room_proto = out.File
	file_room_room_proto_goTypes = nil
	file_room_room_proto_depIdxs = nil
}
