// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: service/game_service.proto

package pb_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameLogic_ForwardClientMsg_FullMethodName     = "/service.GameLogic/ForwardClientMsg"
	GameLogic_ForwardClientRoomMsg_FullMethodName = "/service.GameLogic/ForwardClientRoomMsg"
)

// GameLogicClient is the client API for GameLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Game 提供给 Gate 的转发服务
type GameLogicClient interface {
	// 普通消息转发
	ForwardClientMsg(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardRsp, error)
	// 房间消息转发
	ForwardClientRoomMsg(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardRsp, error)
}

type gameLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewGameLogicClient(cc grpc.ClientConnInterface) GameLogicClient {
	return &gameLogicClient{cc}
}

func (c *gameLogicClient) ForwardClientMsg(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRsp)
	err := c.cc.Invoke(ctx, GameLogic_ForwardClientMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameLogicClient) ForwardClientRoomMsg(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRsp)
	err := c.cc.Invoke(ctx, GameLogic_ForwardClientRoomMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameLogicServer is the server API for GameLogic service.
// All implementations must embed UnimplementedGameLogicServer
// for forward compatibility.
//
// Game 提供给 Gate 的转发服务
type GameLogicServer interface {
	// 普通消息转发
	ForwardClientMsg(context.Context, *ForwardReq) (*ForwardRsp, error)
	// 房间消息转发
	ForwardClientRoomMsg(context.Context, *ForwardReq) (*ForwardRsp, error)
	mustEmbedUnimplementedGameLogicServer()
}

// UnimplementedGameLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameLogicServer struct{}

func (UnimplementedGameLogicServer) ForwardClientMsg(context.Context, *ForwardReq) (*ForwardRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardClientMsg not implemented")
}
func (UnimplementedGameLogicServer) ForwardClientRoomMsg(context.Context, *ForwardReq) (*ForwardRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardClientRoomMsg not implemented")
}
func (UnimplementedGameLogicServer) mustEmbedUnimplementedGameLogicServer() {}
func (UnimplementedGameLogicServer) testEmbeddedByValue()                   {}

// UnsafeGameLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameLogicServer will
// result in compilation errors.
type UnsafeGameLogicServer interface {
	mustEmbedUnimplementedGameLogicServer()
}

func RegisterGameLogicServer(s grpc.ServiceRegistrar, srv GameLogicServer) {
	// If the following call panics, it indicates UnimplementedGameLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameLogic_ServiceDesc, srv)
}

func _GameLogic_ForwardClientMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicServer).ForwardClientMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogic_ForwardClientMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicServer).ForwardClientMsg(ctx, req.(*ForwardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameLogic_ForwardClientRoomMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicServer).ForwardClientRoomMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogic_ForwardClientRoomMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicServer).ForwardClientRoomMsg(ctx, req.(*ForwardReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameLogic_ServiceDesc is the grpc.ServiceDesc for GameLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.GameLogic",
	HandlerType: (*GameLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardClientMsg",
			Handler:    _GameLogic_ForwardClientMsg_Handler,
		},
		{
			MethodName: "ForwardClientRoomMsg",
			Handler:    _GameLogic_ForwardClientRoomMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/game_service.proto",
}
