// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service/game_service.proto

package pb_service

import (
	base "github.com/k8s/muyi/api/pb/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *base.ReqBody          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"` //请求参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReq) Reset() {
	*x = ForwardReq{}
	mi := &file_service_game_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReq) ProtoMessage() {}

func (x *ForwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_game_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReq.ProtoReflect.Descriptor instead.
func (*ForwardReq) Descriptor() ([]byte, []int) {
	return file_service_game_service_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardReq) GetReq() *base.ReqBody {
	if x != nil {
		return x.Req
	}
	return nil
}

type ForwardRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrCode           `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Body          *base.RespBody         `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"` // 返回数据结构体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRsp) Reset() {
	*x = ForwardRsp{}
	mi := &file_service_game_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRsp) ProtoMessage() {}

func (x *ForwardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_game_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRsp.ProtoReflect.Descriptor instead.
func (*ForwardRsp) Descriptor() ([]byte, []int) {
	return file_service_game_service_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRsp) GetCode() base.ErrCode {
	if x != nil {
		return x.Code
	}
	return base.ErrCode(0)
}

func (x *ForwardRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ForwardRsp) GetBody() *base.RespBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_service_game_service_proto protoreflect.FileDescriptor

const file_service_game_service_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/game_service.proto\x12\aservice\x1a\x0fbase/base.proto\"-\n" +
	"\n" +
	"ForwardReq\x12\x1f\n" +
	"\x03req\x18\x01 \x01(\v2\r.base.ReqBodyR\x03req\"e\n" +
	"\n" +
	"ForwardRsp\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.base.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\"\n" +
	"\x04body\x18\x03 \x01(\v2\x0e.base.RespBodyR\x04body2I\n" +
	"\tGameLogic\x12<\n" +
	"\x10ForwardClientMsg\x12\x13.service.ForwardReq\x1a\x13.service.ForwardRspB;Z9github.com/k8s/muyi/k8s-project/api/pb/service;pb_serviceb\x06proto3"

var (
	file_service_game_service_proto_rawDescOnce sync.Once
	file_service_game_service_proto_rawDescData []byte
)

func file_service_game_service_proto_rawDescGZIP() []byte {
	file_service_game_service_proto_rawDescOnce.Do(func() {
		file_service_game_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_game_service_proto_rawDesc), len(file_service_game_service_proto_rawDesc)))
	})
	return file_service_game_service_proto_rawDescData
}

var file_service_game_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_game_service_proto_goTypes = []any{
	(*ForwardReq)(nil),    // 0: service.ForwardReq
	(*ForwardRsp)(nil),    // 1: service.ForwardRsp
	(*base.ReqBody)(nil),  // 2: base.ReqBody
	(base.ErrCode)(0),     // 3: base.ErrCode
	(*base.RespBody)(nil), // 4: base.RespBody
}
var file_service_game_service_proto_depIdxs = []int32{
	2, // 0: service.ForwardReq.req:type_name -> base.ReqBody
	3, // 1: service.ForwardRsp.code:type_name -> base.ErrCode
	4, // 2: service.ForwardRsp.body:type_name -> base.RespBody
	0, // 3: service.GameLogic.ForwardClientMsg:input_type -> service.ForwardReq
	1, // 4: service.GameLogic.ForwardClientMsg:output_type -> service.ForwardRsp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_game_service_proto_init() }
func file_service_game_service_proto_init() {
	if File_service_game_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_game_service_proto_rawDesc), len(file_service_game_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_game_service_proto_goTypes,
		DependencyIndexes: file_service_game_service_proto_depIdxs,
		MessageInfos:      file_service_game_service_proto_msgTypes,
	}.Build()
	File_service_game_service_proto = out.File
	file_service_game_service_proto_goTypes = nil
	file_service_game_service_proto_depIdxs = nil
}
