// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service/gate_service.proto

package pb_service

import (
	base "github.com/k8s/muyi/api/pb/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /--------------push 请求
type PushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *base.PushBody         `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`         //推送基础数据
	Uids          []uint64               `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"` // 推送目标uid 列表 正常至少有一个元素。 如果为空 全服推送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReq) Reset() {
	*x = PushReq{}
	mi := &file_service_gate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReq) ProtoMessage() {}

func (x *PushReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReq.ProtoReflect.Descriptor instead.
func (*PushReq) Descriptor() ([]byte, []int) {
	return file_service_gate_service_proto_rawDescGZIP(), []int{0}
}

func (x *PushReq) GetBody() *base.PushBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushReq) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type PushResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResp) Reset() {
	*x = PushResp{}
	mi := &file_service_gate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResp) ProtoMessage() {}

func (x *PushResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResp.ProtoReflect.Descriptor instead.
func (*PushResp) Descriptor() ([]byte, []int) {
	return file_service_gate_service_proto_rawDescGZIP(), []int{1}
}

func (x *PushResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_service_gate_service_proto protoreflect.FileDescriptor

const file_service_gate_service_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/gate_service.proto\x12\aservice\x1a\x0fbase/base.proto\"A\n" +
	"\aPushReq\x12\"\n" +
	"\x04body\x18\x01 \x01(\v2\x0e.base.PushBodyR\x04body\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\x04R\x04uids\"\x1e\n" +
	"\bPushResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code27\n" +
	"\bGatePush\x12+\n" +
	"\x04Push\x12\x10.service.PushReq\x1a\x11.service.PushRespB;Z9github.com/k8s/muyi/k8s-project/api/pb/service;pb_serviceb\x06proto3"

var (
	file_service_gate_service_proto_rawDescOnce sync.Once
	file_service_gate_service_proto_rawDescData []byte
)

func file_service_gate_service_proto_rawDescGZIP() []byte {
	file_service_gate_service_proto_rawDescOnce.Do(func() {
		file_service_gate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_gate_service_proto_rawDesc), len(file_service_gate_service_proto_rawDesc)))
	})
	return file_service_gate_service_proto_rawDescData
}

var file_service_gate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_gate_service_proto_goTypes = []any{
	(*PushReq)(nil),       // 0: service.PushReq
	(*PushResp)(nil),      // 1: service.PushResp
	(*base.PushBody)(nil), // 2: base.PushBody
}
var file_service_gate_service_proto_depIdxs = []int32{
	2, // 0: service.PushReq.body:type_name -> base.PushBody
	0, // 1: service.GatePush.Push:input_type -> service.PushReq
	1, // 2: service.GatePush.Push:output_type -> service.PushResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_gate_service_proto_init() }
func file_service_gate_service_proto_init() {
	if File_service_gate_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_gate_service_proto_rawDesc), len(file_service_gate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gate_service_proto_goTypes,
		DependencyIndexes: file_service_gate_service_proto_depIdxs,
		MessageInfos:      file_service_gate_service_proto_msgTypes,
	}.Build()
	File_service_gate_service_proto = out.File
	file_service_gate_service_proto_goTypes = nil
	file_service_gate_service_proto_depIdxs = nil
}
