// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: service/gate_service.proto

package pb_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatePush_Push_FullMethodName = "/service.GatePush/Push"
)

// GatePushClient is the client API for GatePush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gate 提供给 Game 的推送服务（题目指定一元RPC Push）
type GatePushClient interface {
	Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error)
}

type gatePushClient struct {
	cc grpc.ClientConnInterface
}

func NewGatePushClient(cc grpc.ClientConnInterface) GatePushClient {
	return &gatePushClient{cc}
}

func (c *gatePushClient) Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResp)
	err := c.cc.Invoke(ctx, GatePush_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatePushServer is the server API for GatePush service.
// All implementations must embed UnimplementedGatePushServer
// for forward compatibility.
//
// Gate 提供给 Game 的推送服务（题目指定一元RPC Push）
type GatePushServer interface {
	Push(context.Context, *PushReq) (*PushResp, error)
	mustEmbedUnimplementedGatePushServer()
}

// UnimplementedGatePushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatePushServer struct{}

func (UnimplementedGatePushServer) Push(context.Context, *PushReq) (*PushResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGatePushServer) mustEmbedUnimplementedGatePushServer() {}
func (UnimplementedGatePushServer) testEmbeddedByValue()                  {}

// UnsafeGatePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatePushServer will
// result in compilation errors.
type UnsafeGatePushServer interface {
	mustEmbedUnimplementedGatePushServer()
}

func RegisterGatePushServer(s grpc.ServiceRegistrar, srv GatePushServer) {
	// If the following call panics, it indicates UnimplementedGatePushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatePush_ServiceDesc, srv)
}

func _GatePush_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatePushServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatePush_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatePushServer).Push(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatePush_ServiceDesc is the grpc.ServiceDesc for GatePush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatePush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.GatePush",
	HandlerType: (*GatePushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _GatePush_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/gate_service.proto",
}
