// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: service/push_service.proto

package pb_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushService_SendPushEvents_FullMethodName = "/service.PushService/SendPushEvents"
	PushService_PushStream_FullMethodName     = "/service.PushService/PushStream"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 推送服务
type PushServiceClient interface {
	// GameServer → PushServer：客户端流（支持批量）
	SendPushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushEvent, PushResponse], error)
	// PushServer ↔ GateServer：双向流
	PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GateToPush, PushToGate], error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) SendPushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushEvent, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PushService_ServiceDesc.Streams[0], PushService_SendPushEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushEvent, PushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_SendPushEventsClient = grpc.ClientStreamingClient[PushEvent, PushResponse]

func (c *pushServiceClient) PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GateToPush, PushToGate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PushService_ServiceDesc.Streams[1], PushService_PushStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GateToPush, PushToGate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_PushStreamClient = grpc.BidiStreamingClient[GateToPush, PushToGate]

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility.
//
// 推送服务
type PushServiceServer interface {
	// GameServer → PushServer：客户端流（支持批量）
	SendPushEvents(grpc.ClientStreamingServer[PushEvent, PushResponse]) error
	// PushServer ↔ GateServer：双向流
	PushStream(grpc.BidiStreamingServer[GateToPush, PushToGate]) error
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServiceServer struct{}

func (UnimplementedPushServiceServer) SendPushEvents(grpc.ClientStreamingServer[PushEvent, PushResponse]) error {
	return status.Error(codes.Unimplemented, "method SendPushEvents not implemented")
}
func (UnimplementedPushServiceServer) PushStream(grpc.BidiStreamingServer[GateToPush, PushToGate]) error {
	return status.Error(codes.Unimplemented, "method PushStream not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}
func (UnimplementedPushServiceServer) testEmbeddedByValue()                     {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	// If the following call panics, it indicates UnimplementedPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_SendPushEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PushServiceServer).SendPushEvents(&grpc.GenericServerStream[PushEvent, PushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_SendPushEventsServer = grpc.ClientStreamingServer[PushEvent, PushResponse]

func _PushService_PushStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PushServiceServer).PushStream(&grpc.GenericServerStream[GateToPush, PushToGate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_PushStreamServer = grpc.BidiStreamingServer[GateToPush, PushToGate]

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPushEvents",
			Handler:       _PushService_SendPushEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushStream",
			Handler:       _PushService_PushStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service/push_service.proto",
}
