// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service/push_service.proto

package pb_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`     // 事件唯一ID
	SendUid       uint64                 `protobuf:"varint,2,opt,name=send_uid,json=sendUid,proto3" json:"send_uid,omitempty"`    //发送者uid
	Uids          []uint64               `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"`                  // 要发送给多个用户， 也可以一个
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                    //发送内容
	ExpireAt      int64                  `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` // 过期时间（秒）
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 发送时间 （秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	mi := &file_service_push_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{0}
}

func (x *PushEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PushEvent) GetSendUid() uint64 {
	if x != nil {
		return x.SendUid
	}
	return 0
}

func (x *PushEvent) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *PushEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEvent) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PushEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_service_push_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Gate → Push（上报）
type GateToPush struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GateToPush_Online
	//	*GateToPush_Offline
	//	*GateToPush_Ack
	Payload       isGateToPush_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateToPush) Reset() {
	*x = GateToPush{}
	mi := &file_service_push_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateToPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateToPush) ProtoMessage() {}

func (x *GateToPush) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateToPush.ProtoReflect.Descriptor instead.
func (*GateToPush) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{2}
}

func (x *GateToPush) GetPayload() isGateToPush_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GateToPush) GetOnline() *Online {
	if x != nil {
		if x, ok := x.Payload.(*GateToPush_Online); ok {
			return x.Online
		}
	}
	return nil
}

func (x *GateToPush) GetOffline() *Offline {
	if x != nil {
		if x, ok := x.Payload.(*GateToPush_Offline); ok {
			return x.Offline
		}
	}
	return nil
}

func (x *GateToPush) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*GateToPush_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isGateToPush_Payload interface {
	isGateToPush_Payload()
}

type GateToPush_Online struct {
	Online *Online `protobuf:"bytes,1,opt,name=online,proto3,oneof"`
}

type GateToPush_Offline struct {
	Offline *Offline `protobuf:"bytes,2,opt,name=offline,proto3,oneof"`
}

type GateToPush_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*GateToPush_Online) isGateToPush_Payload() {}

func (*GateToPush_Offline) isGateToPush_Payload() {}

func (*GateToPush_Ack) isGateToPush_Payload() {}

type Online struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GateAddress   string                 `protobuf:"bytes,2,opt,name=gate_address,json=gateAddress,proto3" json:"gate_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Online) Reset() {
	*x = Online{}
	mi := &file_service_push_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Online) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Online) ProtoMessage() {}

func (x *Online) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Online.ProtoReflect.Descriptor instead.
func (*Online) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{3}
}

func (x *Online) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Online) GetGateAddress() string {
	if x != nil {
		return x.GateAddress
	}
	return ""
}

type Offline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offline) Reset() {
	*x = Offline{}
	mi := &file_service_push_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{4}
}

func (x *Offline) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Offline) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_service_push_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Ack) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Push → Gate（下发，支持批量）
type PushToGate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Uids          []uint64               `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"` // 支持批量下发
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToGate) Reset() {
	*x = PushToGate{}
	mi := &file_service_push_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToGate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToGate) ProtoMessage() {}

func (x *PushToGate) ProtoReflect() protoreflect.Message {
	mi := &file_service_push_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToGate.ProtoReflect.Descriptor instead.
func (*PushToGate) Descriptor() ([]byte, []int) {
	return file_service_push_service_proto_rawDescGZIP(), []int{6}
}

func (x *PushToGate) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PushToGate) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *PushToGate) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *PushToGate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_service_push_service_proto protoreflect.FileDescriptor

const file_service_push_service_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/push_service.proto\x12\aservice\"\xaa\x01\n" +
	"\tPushEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bsend_uid\x18\x02 \x01(\x04R\asendUid\x12\x12\n" +
	"\x04uids\x18\x03 \x03(\x04R\x04uids\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x03R\bexpireAt\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"U\n" +
	"\fPushResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x92\x01\n" +
	"\n" +
	"GateToPush\x12)\n" +
	"\x06online\x18\x01 \x01(\v2\x0f.service.OnlineH\x00R\x06online\x12,\n" +
	"\aoffline\x18\x02 \x01(\v2\x10.service.OfflineH\x00R\aoffline\x12 \n" +
	"\x03ack\x18\x03 \x01(\v2\f.service.AckH\x00R\x03ackB\t\n" +
	"\apayload\"D\n" +
	"\x06Online\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fgate_address\x18\x02 \x01(\tR\vgateAddress\":\n" +
	"\aOffline\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"9\n" +
	"\x03Ack\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"p\n" +
	"\n" +
	"PushToGate\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\x04R\x04uids\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2\x88\x01\n" +
	"\vPushService\x12=\n" +
	"\x0eSendPushEvents\x12\x12.service.PushEvent\x1a\x15.service.PushResponse(\x01\x12:\n" +
	"\n" +
	"PushStream\x12\x13.service.GateToPush\x1a\x13.service.PushToGate(\x010\x01B;Z9github.com/k8s/muyi/k8s-project/api/pb/service;pb_serviceb\x06proto3"

var (
	file_service_push_service_proto_rawDescOnce sync.Once
	file_service_push_service_proto_rawDescData []byte
)

func file_service_push_service_proto_rawDescGZIP() []byte {
	file_service_push_service_proto_rawDescOnce.Do(func() {
		file_service_push_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_push_service_proto_rawDesc), len(file_service_push_service_proto_rawDesc)))
	})
	return file_service_push_service_proto_rawDescData
}

var file_service_push_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_push_service_proto_goTypes = []any{
	(*PushEvent)(nil),    // 0: service.PushEvent
	(*PushResponse)(nil), // 1: service.PushResponse
	(*GateToPush)(nil),   // 2: service.GateToPush
	(*Online)(nil),       // 3: service.Online
	(*Offline)(nil),      // 4: service.Offline
	(*Ack)(nil),          // 5: service.Ack
	(*PushToGate)(nil),   // 6: service.PushToGate
}
var file_service_push_service_proto_depIdxs = []int32{
	3, // 0: service.GateToPush.online:type_name -> service.Online
	4, // 1: service.GateToPush.offline:type_name -> service.Offline
	5, // 2: service.GateToPush.ack:type_name -> service.Ack
	0, // 3: service.PushService.SendPushEvents:input_type -> service.PushEvent
	2, // 4: service.PushService.PushStream:input_type -> service.GateToPush
	1, // 5: service.PushService.SendPushEvents:output_type -> service.PushResponse
	6, // 6: service.PushService.PushStream:output_type -> service.PushToGate
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_push_service_proto_init() }
func file_service_push_service_proto_init() {
	if File_service_push_service_proto != nil {
		return
	}
	file_service_push_service_proto_msgTypes[2].OneofWrappers = []any{
		(*GateToPush_Online)(nil),
		(*GateToPush_Offline)(nil),
		(*GateToPush_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_push_service_proto_rawDesc), len(file_service_push_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_push_service_proto_goTypes,
		DependencyIndexes: file_service_push_service_proto_depIdxs,
		MessageInfos:      file_service_push_service_proto_msgTypes,
	}.Build()
	File_service_push_service_proto = out.File
	file_service_push_service_proto_goTypes = nil
	file_service_push_service_proto_depIdxs = nil
}
