apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeout: 30
      nativeHistogramMode: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      timeout: 30
      maxLines: 2000
      derivedFields:
        - name: TraceID
          type: regex
          matcherRegex: '"trace_id":"([0-9a-f]{32})"'
          url: '$${__value.raw}'  # ✅ YAML 必须写 $$ 转义
          datasourceUid: tempo
          internalLink: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
        # 先删掉手动 tags 映射！避免格式报错
      serviceMap:
        datasourceUid: prometheus
