// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: web/user.proto

package pb_web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserInfoReq) Reset() {
	*x = SyncUserInfoReq{}
	mi := &file_web_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserInfoReq) ProtoMessage() {}

func (x *SyncUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserInfoReq.ProtoReflect.Descriptor instead.
func (*SyncUserInfoReq) Descriptor() ([]byte, []int) {
	return file_web_user_proto_rawDescGZIP(), []int{0}
}

type SyncUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserInfoResp) Reset() {
	*x = SyncUserInfoResp{}
	mi := &file_web_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserInfoResp) ProtoMessage() {}

func (x *SyncUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserInfoResp.ProtoReflect.Descriptor instead.
func (*SyncUserInfoResp) Descriptor() ([]byte, []int) {
	return file_web_user_proto_rawDescGZIP(), []int{1}
}

var File_web_user_proto protoreflect.FileDescriptor

const file_web_user_proto_rawDesc = "" +
	"\n" +
	"\x0eweb/user.proto\x12\x03web\"\x11\n" +
	"\x0fSyncUserInfoReq\"\x12\n" +
	"\x10SyncUserInfoRespB\rZ\v/web;pb_webb\x06proto3"

var (
	file_web_user_proto_rawDescOnce sync.Once
	file_web_user_proto_rawDescData []byte
)

func file_web_user_proto_rawDescGZIP() []byte {
	file_web_user_proto_rawDescOnce.Do(func() {
		file_web_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_user_proto_rawDesc), len(file_web_user_proto_rawDesc)))
	})
	return file_web_user_proto_rawDescData
}

var file_web_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_web_user_proto_goTypes = []any{
	(*SyncUserInfoReq)(nil),  // 0: web.SyncUserInfoReq
	(*SyncUserInfoResp)(nil), // 1: web.SyncUserInfoResp
}
var file_web_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_web_user_proto_init() }
func file_web_user_proto_init() {
	if File_web_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_user_proto_rawDesc), len(file_web_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_user_proto_goTypes,
		DependencyIndexes: file_web_user_proto_depIdxs,
		MessageInfos:      file_web_user_proto_msgTypes,
	}.Build()
	File_web_user_proto = out.File
	file_web_user_proto_goTypes = nil
	file_web_user_proto_depIdxs = nil
}
