// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: base/base.proto

package pb_base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息大类
type FrameType int32

const (
	FrameType_FRAME_UNKNOWN  FrameType = 0
	FrameType_FRAME_REQUEST  FrameType = 1 // 客户端主动请求
	FrameType_FRAME_RESPONSE FrameType = 2 // 网关回包响应
	FrameType_FRAME_PUSH     FrameType = 3 // 服务端主动推送
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_UNKNOWN",
		1: "FRAME_REQUEST",
		2: "FRAME_RESPONSE",
		3: "FRAME_PUSH",
	}
	FrameType_value = map[string]int32{
		"FRAME_UNKNOWN":  0,
		"FRAME_REQUEST":  1,
		"FRAME_RESPONSE": 2,
		"FRAME_PUSH":     3,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{0}
}

// 业务大类
type FirstKind int32

const (
	FirstKind_FIRST_UNKNOW FirstKind = 0
	FirstKind_FIRST_ROOM   FirstKind = 1 //路由到room 服务
	FirstKind_FIRST_GUILD  FirstKind = 2 //路由到guild 公会服务
)

// Enum value maps for FirstKind.
var (
	FirstKind_name = map[int32]string{
		0: "FIRST_UNKNOW",
		1: "FIRST_ROOM",
		2: "FIRST_GUILD",
	}
	FirstKind_value = map[string]int32{
		"FIRST_UNKNOW": 0,
		"FIRST_ROOM":   1,
		"FIRST_GUILD":  2,
	}
)

func (x FirstKind) Enum() *FirstKind {
	p := new(FirstKind)
	*p = x
	return p
}

func (x FirstKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirstKind) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[1].Descriptor()
}

func (FirstKind) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[1]
}

func (x FirstKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirstKind.Descriptor instead.
func (FirstKind) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{1}
}

// 业务小类接口
type CmdKind int32

const (
	CmdKind_Cmd_UNKNOW      CmdKind = 0
	CmdKind_CMD_CREATE_ROOM CmdKind = 1 // 创建房间
)

// Enum value maps for CmdKind.
var (
	CmdKind_name = map[int32]string{
		0: "Cmd_UNKNOW",
		1: "CMD_CREATE_ROOM",
	}
	CmdKind_value = map[string]int32{
		"Cmd_UNKNOW":      0,
		"CMD_CREATE_ROOM": 1,
	}
)

func (x CmdKind) Enum() *CmdKind {
	p := new(CmdKind)
	*p = x
	return p
}

func (x CmdKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdKind) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[2].Descriptor()
}

func (CmdKind) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[2]
}

func (x CmdKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdKind.Descriptor instead.
func (CmdKind) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{2}
}

// 全局错误码
type ErrCode int32

const (
	ErrCode_EC_OK                  ErrCode = 0
	ErrCode_EC_INTERNAL_ERR        ErrCode = 10001
	ErrCode_EC_PARAM_INVALID       ErrCode = 10002
	ErrCode_EC_USER_NOT_LOGIN      ErrCode = 10003
	ErrCode_EC_ROOM_NOT_EXIST      ErrCode = 10004
	ErrCode_EC_ROOM_FULL           ErrCode = 10005
	ErrCode_EC_GAME_SERVER_UNAVAIL ErrCode = 10006
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "EC_OK",
		10001: "EC_INTERNAL_ERR",
		10002: "EC_PARAM_INVALID",
		10003: "EC_USER_NOT_LOGIN",
		10004: "EC_ROOM_NOT_EXIST",
		10005: "EC_ROOM_FULL",
		10006: "EC_GAME_SERVER_UNAVAIL",
	}
	ErrCode_value = map[string]int32{
		"EC_OK":                  0,
		"EC_INTERNAL_ERR":        10001,
		"EC_PARAM_INVALID":       10002,
		"EC_USER_NOT_LOGIN":      10003,
		"EC_ROOM_NOT_EXIST":      10004,
		"EC_ROOM_FULL":           10005,
		"EC_GAME_SERVER_UNAVAIL": 10006,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[3].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[3]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{3}
}

// 顶层统一包裹帧
type WsFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameType     FrameType              `protobuf:"varint,1,opt,name=frame_type,json=frameType,proto3,enum=base.FrameType" json:"frame_type,omitempty"` //
	FirstKind     FirstKind              `protobuf:"varint,2,opt,name=first_kind,json=firstKind,proto3,enum=base.FirstKind" json:"first_kind,omitempty"` //
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                                                  // 请求序列号，响应原样带回，客户端异步匹配
	Uid           uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`                                                  // 用户ID
	ErrCode       ErrCode                `protobuf:"varint,5,opt,name=err_code,json=errCode,proto3,enum=base.ErrCode" json:"err_code,omitempty"`         // 错误码
	ErrMsg        string                 `protobuf:"bytes,6,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`                               // 错误详情
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                                           // 业务子消息序列化数据
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // 客户端原样ts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsFrame) Reset() {
	*x = WsFrame{}
	mi := &file_base_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsFrame) ProtoMessage() {}

func (x *WsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsFrame.ProtoReflect.Descriptor instead.
func (*WsFrame) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *WsFrame) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_UNKNOWN
}

func (x *WsFrame) GetFirstKind() FirstKind {
	if x != nil {
		return x.FirstKind
	}
	return FirstKind_FIRST_UNKNOW
}

func (x *WsFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WsFrame) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WsFrame) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_EC_OK
}

func (x *WsFrame) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *WsFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 客户端请求体 (body填充)
type ReqBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"` // 业务指令:1进房 2发消息 3退房 在 业务中也用 枚举定义 比直接约定 1，2，3 这种要好
	Uid           uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 业务参数结构体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqBody) Reset() {
	*x = ReqBody{}
	mi := &file_base_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBody) ProtoMessage() {}

func (x *ReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBody.ProtoReflect.Descriptor instead.
func (*ReqBody) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *ReqBody) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ReqBody) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqBody) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 网关响应体 (body填充)
type RespBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 实际返回业务数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespBody) Reset() {
	*x = RespBody{}
	mi := &file_base_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBody) ProtoMessage() {}

func (x *RespBody) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBody.ProtoReflect.Descriptor instead.
func (*RespBody) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{2}
}

func (x *RespBody) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *RespBody) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 服务推送体 (Game->Gate->Client)
type PushBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 业务数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBody) Reset() {
	*x = PushBody{}
	mi := &file_base_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBody) ProtoMessage() {}

func (x *PushBody) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBody.ProtoReflect.Descriptor instead.
func (*PushBody) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{3}
}

func (x *PushBody) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *PushBody) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_base_base_proto protoreflect.FileDescriptor

const file_base_base_proto_rawDesc = "" +
	"\n" +
	"\x0fbase/base.proto\x12\x04base\"\x88\x02\n" +
	"\aWsFrame\x12.\n" +
	"\n" +
	"frame_type\x18\x01 \x01(\x0e2\x0f.base.FrameTypeR\tframeType\x12.\n" +
	"\n" +
	"first_kind\x18\x02 \x01(\x0e2\x0f.base.FirstKindR\tfirstKind\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\x12(\n" +
	"\berr_code\x18\x05 \x01(\x0e2\r.base.ErrCodeR\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x06 \x01(\tR\x06errMsg\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"G\n" +
	"\aReqBody\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\rR\x03cmd\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"6\n" +
	"\bRespBody\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\rR\x03cmd\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"6\n" +
	"\bPushBody\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\rR\x03cmd\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload*U\n" +
	"\tFrameType\x12\x11\n" +
	"\rFRAME_UNKNOWN\x10\x00\x12\x11\n" +
	"\rFRAME_REQUEST\x10\x01\x12\x12\n" +
	"\x0eFRAME_RESPONSE\x10\x02\x12\x0e\n" +
	"\n" +
	"FRAME_PUSH\x10\x03*>\n" +
	"\tFirstKind\x12\x10\n" +
	"\fFIRST_UNKNOW\x10\x00\x12\x0e\n" +
	"\n" +
	"FIRST_ROOM\x10\x01\x12\x0f\n" +
	"\vFIRST_GUILD\x10\x02*.\n" +
	"\aCmdKind\x12\x0e\n" +
	"\n" +
	"Cmd_UNKNOW\x10\x00\x12\x13\n" +
	"\x0fCMD_CREATE_ROOM\x10\x01*\xa1\x01\n" +
	"\aErrCode\x12\t\n" +
	"\x05EC_OK\x10\x00\x12\x14\n" +
	"\x0fEC_INTERNAL_ERR\x10\x91N\x12\x15\n" +
	"\x10EC_PARAM_INVALID\x10\x92N\x12\x16\n" +
	"\x11EC_USER_NOT_LOGIN\x10\x93N\x12\x16\n" +
	"\x11EC_ROOM_NOT_EXIST\x10\x94N\x12\x11\n" +
	"\fEC_ROOM_FULL\x10\x95N\x12\x1b\n" +
	"\x16EC_GAME_SERVER_UNAVAIL\x10\x96NB)Z'github.com/k8s/muyi/api/pb/base;pb_baseb\x06proto3"

var (
	file_base_base_proto_rawDescOnce sync.Once
	file_base_base_proto_rawDescData []byte
)

func file_base_base_proto_rawDescGZIP() []byte {
	file_base_base_proto_rawDescOnce.Do(func() {
		file_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)))
	})
	return file_base_base_proto_rawDescData
}

var file_base_base_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_base_base_proto_goTypes = []any{
	(FrameType)(0),   // 0: base.FrameType
	(FirstKind)(0),   // 1: base.FirstKind
	(CmdKind)(0),     // 2: base.CmdKind
	(ErrCode)(0),     // 3: base.ErrCode
	(*WsFrame)(nil),  // 4: base.WsFrame
	(*ReqBody)(nil),  // 5: base.ReqBody
	(*RespBody)(nil), // 6: base.RespBody
	(*PushBody)(nil), // 7: base.PushBody
}
var file_base_base_proto_depIdxs = []int32{
	0, // 0: base.WsFrame.frame_type:type_name -> base.FrameType
	1, // 1: base.WsFrame.first_kind:type_name -> base.FirstKind
	3, // 2: base.WsFrame.err_code:type_name -> base.ErrCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_base_base_proto_init() }
func file_base_base_proto_init() {
	if File_base_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_base_proto_goTypes,
		DependencyIndexes: file_base_base_proto_depIdxs,
		EnumInfos:         file_base_base_proto_enumTypes,
		MessageInfos:      file_base_base_proto_msgTypes,
	}.Build()
	File_base_base_proto = out.File
	file_base_base_proto_goTypes = nil
	file_base_base_proto_depIdxs = nil
}
