apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-web-cm
  namespace: default
data:
  config.toml: |
    [serverinfo]
    projectName = "racer"
    serverId = "1001"
    env ="prod"
    jwtSecret = ""

    [redis]
    host = "redis-svc"
    port = "6379"
    password = ""
    db = 0
    poolSize = 300

    [mysql]
    host = "mysql-svc"
    port = 3306
    user = ""
    password = ""
    dbname = "racer_db"
    max_idle_conns = 10
    max_open_conns = 100
    conn_max_lifetime = "5m"
    is_open_auto_migration = false
    slowThreshold = 1000
    level= "Warn"

    [log]
    debug = false
    maxSize = 500
    maxDays = 30
    maxBackups = 10
    fileName = "/dev/stdout"
    compress = false
    rotateByDay = true
    logLevel = "info"
    needErrLog = false
    errLogPath = ""

    [etcd]
    endpoints = ["http://etcd-svc:2379"]
    dialTimeout =10
    ttl=15
    keepAliveInterval=5
    username  =""
    password  =""