apiVersion: v1
kind: Secret
metadata:
  name: k8s-web-secret
  namespace: default
type: Opaque
data:
  JWT_SECRET: NzktWRtLc3lfZ3BJRGsZWWxybVdnb3hSdFRETVVEaG55LVRCaXVGODM3V0M9Cg==
  REDIS_PASSWORD: MTIzNDU2
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: MTIzNDU2
  ETCD_USER: ""
  ETCD_PASSWORD: ""