// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cpp_features.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from cpp_features.proto</summary>
  public static partial class CppFeaturesReflection {

    #region Descriptor
    /// <summary>File descriptor for cpp_features.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CppFeaturesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJjcHBfZmVhdHVyZXMucHJvdG8SAnBiGiBnb29nbGUvcHJvdG9idWYvZGVz",
            "Y3JpcHRvci5wcm90byL8AwoLQ3BwRmVhdHVyZXMS+wEKEmxlZ2FjeV9jbG9z",
            "ZWRfZW51bRgBIAEoCELeAYgBAZgBBJgBAaIBCRIEdHJ1ZRiEB6IBChIFZmFs",
            "c2UY5weyAbgBCOgHEOgHGq8BVGhlIGxlZ2FjeSBjbG9zZWQgZW51bSBiZWhh",
            "dmlvciBpbiBDKysgaXMgZGVwcmVjYXRlZCBhbmQgaXMgc2NoZWR1bGVkIHRv",
            "IGJlIHJlbW92ZWQgaW4gZWRpdGlvbiAyMDI1LiAgU2VlIGh0dHA6Ly9wcm90",
            "b2J1Zi5kZXYvcHJvZ3JhbW1pbmctZ3VpZGVzL2VudW0vI2NwcCBmb3IgbW9y",
            "ZSBpbmZvcm1hdGlvbhJaCgtzdHJpbmdfdHlwZRgCIAEoDjIaLnBiLkNwcEZl",
            "YXR1cmVzLlN0cmluZ1R5cGVCKYgBAZgBBJgBAaIBCxIGU1RSSU5HGIQHogEJ",
            "EgRWSUVXGOkHsgEDCOgHEkwKGmVudW1fbmFtZV91c2VzX3N0cmluZ192aWV3",
            "GAMgASgIQiiIAQKYAQaYAQGiAQoSBWZhbHNlGIQHogEJEgR0cnVlGOkHsgED",
            "COkHIkUKClN0cmluZ1R5cGUSFwoTU1RSSU5HX1RZUEVfVU5LTk9XThAAEggK",
            "BFZJRVcQARIICgRDT1JEEAISCgoGU1RSSU5HEAM6OgoDY3BwEhsuZ29vZ2xl",
            "LnByb3RvYnVmLkZlYXR1cmVTZXQY6AcgASgLMg8ucGIuQ3BwRmVhdHVyZXM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { CppFeaturesExtensions.Cpp }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.CppFeatures), global::Pb.CppFeatures.Parser, new[]{ "LegacyClosedEnum", "StringType", "EnumNameUsesStringView" }, null, new[]{ typeof(global::Pb.CppFeatures.Types.StringType) }, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of cpp_features.proto</summary>
  public static partial class CppFeaturesExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.CppFeatures> Cpp =
      new pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.CppFeatures>(1000, pb::FieldCodec.ForMessage(8002, global::Pb.CppFeatures.Parser));
  }

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CppFeatures : pb::IMessage<CppFeatures>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CppFeatures> _parser = new pb::MessageParser<CppFeatures>(() => new CppFeatures());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CppFeatures> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CppFeaturesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CppFeatures() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CppFeatures(CppFeatures other) : this() {
      _hasBits0 = other._hasBits0;
      legacyClosedEnum_ = other.legacyClosedEnum_;
      stringType_ = other.stringType_;
      enumNameUsesStringView_ = other.enumNameUsesStringView_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CppFeatures Clone() {
      return new CppFeatures(this);
    }

    /// <summary>Field number for the "legacy_closed_enum" field.</summary>
    public const int LegacyClosedEnumFieldNumber = 1;
    private readonly static bool LegacyClosedEnumDefaultValue = false;

    private bool legacyClosedEnum_;
    /// <summary>
    /// Whether or not to treat an enum field as closed.  This option is only
    /// applicable to enum fields, and will be removed in the future.  It is
    /// consistent with the legacy behavior of using proto3 enum types for proto2
    /// fields.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LegacyClosedEnum {
      get { if ((_hasBits0 & 1) != 0) { return legacyClosedEnum_; } else { return LegacyClosedEnumDefaultValue; } }
      set {
        _hasBits0 |= 1;
        legacyClosedEnum_ = value;
      }
    }
    /// <summary>Gets whether the "legacy_closed_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLegacyClosedEnum {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "legacy_closed_enum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLegacyClosedEnum() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "string_type" field.</summary>
    public const int StringTypeFieldNumber = 2;
    private readonly static global::Pb.CppFeatures.Types.StringType StringTypeDefaultValue = global::Pb.CppFeatures.Types.StringType.Unknown;

    private global::Pb.CppFeatures.Types.StringType stringType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.CppFeatures.Types.StringType StringType {
      get { if ((_hasBits0 & 2) != 0) { return stringType_; } else { return StringTypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        stringType_ = value;
      }
    }
    /// <summary>Gets whether the "string_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "string_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "enum_name_uses_string_view" field.</summary>
    public const int EnumNameUsesStringViewFieldNumber = 3;
    private readonly static bool EnumNameUsesStringViewDefaultValue = false;

    private bool enumNameUsesStringView_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnumNameUsesStringView {
      get { if ((_hasBits0 & 4) != 0) { return enumNameUsesStringView_; } else { return EnumNameUsesStringViewDefaultValue; } }
      set {
        _hasBits0 |= 4;
        enumNameUsesStringView_ = value;
      }
    }
    /// <summary>Gets whether the "enum_name_uses_string_view" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEnumNameUsesStringView {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "enum_name_uses_string_view" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEnumNameUsesStringView() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CppFeatures);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CppFeatures other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LegacyClosedEnum != other.LegacyClosedEnum) return false;
      if (StringType != other.StringType) return false;
      if (EnumNameUsesStringView != other.EnumNameUsesStringView) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLegacyClosedEnum) hash ^= LegacyClosedEnum.GetHashCode();
      if (HasStringType) hash ^= StringType.GetHashCode();
      if (HasEnumNameUsesStringView) hash ^= EnumNameUsesStringView.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLegacyClosedEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyClosedEnum);
      }
      if (HasStringType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StringType);
      }
      if (HasEnumNameUsesStringView) {
        output.WriteRawTag(24);
        output.WriteBool(EnumNameUsesStringView);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLegacyClosedEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyClosedEnum);
      }
      if (HasStringType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StringType);
      }
      if (HasEnumNameUsesStringView) {
        output.WriteRawTag(24);
        output.WriteBool(EnumNameUsesStringView);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLegacyClosedEnum) {
        size += 1 + 1;
      }
      if (HasStringType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StringType);
      }
      if (HasEnumNameUsesStringView) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CppFeatures other) {
      if (other == null) {
        return;
      }
      if (other.HasLegacyClosedEnum) {
        LegacyClosedEnum = other.LegacyClosedEnum;
      }
      if (other.HasStringType) {
        StringType = other.StringType;
      }
      if (other.HasEnumNameUsesStringView) {
        EnumNameUsesStringView = other.EnumNameUsesStringView;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LegacyClosedEnum = input.ReadBool();
            break;
          }
          case 16: {
            StringType = (global::Pb.CppFeatures.Types.StringType) input.ReadEnum();
            break;
          }
          case 24: {
            EnumNameUsesStringView = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LegacyClosedEnum = input.ReadBool();
            break;
          }
          case 16: {
            StringType = (global::Pb.CppFeatures.Types.StringType) input.ReadEnum();
            break;
          }
          case 24: {
            EnumNameUsesStringView = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CppFeatures message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum StringType {
        [pbr::OriginalName("STRING_TYPE_UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("VIEW")] View = 1,
        [pbr::OriginalName("CORD")] Cord = 2,
        [pbr::OriginalName("STRING")] String = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
