// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: go_features.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from go_features.proto</summary>
  public static partial class GoFeaturesReflection {

    #region Descriptor
    /// <summary>File descriptor for go_features.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GoFeaturesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFnb19mZWF0dXJlcy5wcm90bxICcGIaIGdvb2dsZS9wcm90b2J1Zi9kZXNj",
            "cmlwdG9yLnByb3RvIvcECgpHb0ZlYXR1cmVzEqUBChpsZWdhY3lfdW5tYXJz",
            "aGFsX2pzb25fZW51bRgBIAEoCEKAAYgBAZgBBpgBAaIBCRIEdHJ1ZRiEB6IB",
            "ChIFZmFsc2UY5weyAVsI6AcQ6AcaU1RoZSBsZWdhY3kgVW5tYXJzaGFsSlNP",
            "TiBBUEkgaXMgZGVwcmVjYXRlZCBhbmQgd2lsbCBiZSByZW1vdmVkIGluIGEg",
            "ZnV0dXJlIGVkaXRpb24uEmoKCWFwaV9sZXZlbBgCIAEoDjIXLnBiLkdvRmVh",
            "dHVyZXMuQVBJTGV2ZWxCPogBAZgBA5gBAaIBGhIVQVBJX0xFVkVMX1VOU1BF",
            "Q0lGSUVEGIQHogEPEgpBUElfT1BBUVVFGOkHsgEDCOgHEmsKEXN0cmlwX2Vu",
            "dW1fcHJlZml4GAMgASgOMh4ucGIuR29GZWF0dXJlcy5TdHJpcEVudW1QcmVm",
            "aXhCMIgBAZgBBpgBB5gBAaIBGxIWU1RSSVBfRU5VTV9QUkVGSVhfS0VFUBiE",
            "B7IBAwjpByJTCghBUElMZXZlbBIZChVBUElfTEVWRUxfVU5TUEVDSUZJRUQQ",
            "ABIMCghBUElfT1BFThABEg4KCkFQSV9IWUJSSUQQAhIOCgpBUElfT1BBUVVF",
            "EAMikgEKD1N0cmlwRW51bVByZWZpeBIhCh1TVFJJUF9FTlVNX1BSRUZJWF9V",
            "TlNQRUNJRklFRBAAEhoKFlNUUklQX0VOVU1fUFJFRklYX0tFRVAQARIjCh9T",
            "VFJJUF9FTlVNX1BSRUZJWF9HRU5FUkFURV9CT1RIEAISGwoXU1RSSVBfRU5V",
            "TV9QUkVGSVhfU1RSSVAQAzo4CgJnbxIbLmdvb2dsZS5wcm90b2J1Zi5GZWF0",
            "dXJlU2V0GOoHIAEoCzIOLnBiLkdvRmVhdHVyZXNCL1otZ29vZ2xlLmdvbGFu",
            "Zy5vcmcvcHJvdG9idWYvdHlwZXMvZ29mZWF0dXJlc3Bi"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { GoFeaturesExtensions.Go }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.GoFeatures), global::Pb.GoFeatures.Parser, new[]{ "LegacyUnmarshalJsonEnum", "ApiLevel", "StripEnumPrefix" }, null, new[]{ typeof(global::Pb.GoFeatures.Types.APILevel), typeof(global::Pb.GoFeatures.Types.StripEnumPrefix) }, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of go_features.proto</summary>
  public static partial class GoFeaturesExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.GoFeatures> Go =
      new pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.GoFeatures>(1002, pb::FieldCodec.ForMessage(8018, global::Pb.GoFeatures.Parser));
  }

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GoFeatures : pb::IMessage<GoFeatures>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GoFeatures> _parser = new pb::MessageParser<GoFeatures>(() => new GoFeatures());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GoFeatures> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.GoFeaturesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoFeatures() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoFeatures(GoFeatures other) : this() {
      _hasBits0 = other._hasBits0;
      legacyUnmarshalJsonEnum_ = other.legacyUnmarshalJsonEnum_;
      apiLevel_ = other.apiLevel_;
      stripEnumPrefix_ = other.stripEnumPrefix_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoFeatures Clone() {
      return new GoFeatures(this);
    }

    /// <summary>Field number for the "legacy_unmarshal_json_enum" field.</summary>
    public const int LegacyUnmarshalJsonEnumFieldNumber = 1;
    private readonly static bool LegacyUnmarshalJsonEnumDefaultValue = false;

    private bool legacyUnmarshalJsonEnum_;
    /// <summary>
    /// Whether or not to generate the deprecated UnmarshalJSON method for enums.
    /// Can only be true for proto using the Open Struct api.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LegacyUnmarshalJsonEnum {
      get { if ((_hasBits0 & 1) != 0) { return legacyUnmarshalJsonEnum_; } else { return LegacyUnmarshalJsonEnumDefaultValue; } }
      set {
        _hasBits0 |= 1;
        legacyUnmarshalJsonEnum_ = value;
      }
    }
    /// <summary>Gets whether the "legacy_unmarshal_json_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLegacyUnmarshalJsonEnum {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "legacy_unmarshal_json_enum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLegacyUnmarshalJsonEnum() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "api_level" field.</summary>
    public const int ApiLevelFieldNumber = 2;
    private readonly static global::Pb.GoFeatures.Types.APILevel ApiLevelDefaultValue = global::Pb.GoFeatures.Types.APILevel.Unspecified;

    private global::Pb.GoFeatures.Types.APILevel apiLevel_;
    /// <summary>
    /// One of OPEN, HYBRID or OPAQUE.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.GoFeatures.Types.APILevel ApiLevel {
      get { if ((_hasBits0 & 2) != 0) { return apiLevel_; } else { return ApiLevelDefaultValue; } }
      set {
        _hasBits0 |= 2;
        apiLevel_ = value;
      }
    }
    /// <summary>Gets whether the "api_level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasApiLevel {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "api_level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearApiLevel() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "strip_enum_prefix" field.</summary>
    public const int StripEnumPrefixFieldNumber = 3;
    private readonly static global::Pb.GoFeatures.Types.StripEnumPrefix StripEnumPrefixDefaultValue = global::Pb.GoFeatures.Types.StripEnumPrefix.Unspecified;

    private global::Pb.GoFeatures.Types.StripEnumPrefix stripEnumPrefix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.GoFeatures.Types.StripEnumPrefix StripEnumPrefix {
      get { if ((_hasBits0 & 4) != 0) { return stripEnumPrefix_; } else { return StripEnumPrefixDefaultValue; } }
      set {
        _hasBits0 |= 4;
        stripEnumPrefix_ = value;
      }
    }
    /// <summary>Gets whether the "strip_enum_prefix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStripEnumPrefix {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "strip_enum_prefix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStripEnumPrefix() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GoFeatures);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GoFeatures other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LegacyUnmarshalJsonEnum != other.LegacyUnmarshalJsonEnum) return false;
      if (ApiLevel != other.ApiLevel) return false;
      if (StripEnumPrefix != other.StripEnumPrefix) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLegacyUnmarshalJsonEnum) hash ^= LegacyUnmarshalJsonEnum.GetHashCode();
      if (HasApiLevel) hash ^= ApiLevel.GetHashCode();
      if (HasStripEnumPrefix) hash ^= StripEnumPrefix.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLegacyUnmarshalJsonEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyUnmarshalJsonEnum);
      }
      if (HasApiLevel) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ApiLevel);
      }
      if (HasStripEnumPrefix) {
        output.WriteRawTag(24);
        output.WriteEnum((int) StripEnumPrefix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLegacyUnmarshalJsonEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyUnmarshalJsonEnum);
      }
      if (HasApiLevel) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ApiLevel);
      }
      if (HasStripEnumPrefix) {
        output.WriteRawTag(24);
        output.WriteEnum((int) StripEnumPrefix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLegacyUnmarshalJsonEnum) {
        size += 1 + 1;
      }
      if (HasApiLevel) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ApiLevel);
      }
      if (HasStripEnumPrefix) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StripEnumPrefix);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GoFeatures other) {
      if (other == null) {
        return;
      }
      if (other.HasLegacyUnmarshalJsonEnum) {
        LegacyUnmarshalJsonEnum = other.LegacyUnmarshalJsonEnum;
      }
      if (other.HasApiLevel) {
        ApiLevel = other.ApiLevel;
      }
      if (other.HasStripEnumPrefix) {
        StripEnumPrefix = other.StripEnumPrefix;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LegacyUnmarshalJsonEnum = input.ReadBool();
            break;
          }
          case 16: {
            ApiLevel = (global::Pb.GoFeatures.Types.APILevel) input.ReadEnum();
            break;
          }
          case 24: {
            StripEnumPrefix = (global::Pb.GoFeatures.Types.StripEnumPrefix) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LegacyUnmarshalJsonEnum = input.ReadBool();
            break;
          }
          case 16: {
            ApiLevel = (global::Pb.GoFeatures.Types.APILevel) input.ReadEnum();
            break;
          }
          case 24: {
            StripEnumPrefix = (global::Pb.GoFeatures.Types.StripEnumPrefix) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GoFeatures message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum APILevel {
        /// <summary>
        /// API_LEVEL_UNSPECIFIED results in selecting the OPEN API,
        /// but needs to be a separate value to distinguish between
        /// an explicitly set api level or a missing api level.
        /// </summary>
        [pbr::OriginalName("API_LEVEL_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("API_OPEN")] ApiOpen = 1,
        [pbr::OriginalName("API_HYBRID")] ApiHybrid = 2,
        [pbr::OriginalName("API_OPAQUE")] ApiOpaque = 3,
      }

      public enum StripEnumPrefix {
        [pbr::OriginalName("STRIP_ENUM_PREFIX_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("STRIP_ENUM_PREFIX_KEEP")] Keep = 1,
        [pbr::OriginalName("STRIP_ENUM_PREFIX_GENERATE_BOTH")] GenerateBoth = 2,
        [pbr::OriginalName("STRIP_ENUM_PREFIX_STRIP")] Strip = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
