// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: java_features.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from java_features.proto</summary>
  public static partial class JavaFeaturesReflection {

    #region Descriptor
    /// <summary>File descriptor for java_features.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JavaFeaturesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNqYXZhX2ZlYXR1cmVzLnByb3RvEgJwYhogZ29vZ2xlL3Byb3RvYnVmL2Rl",
            "c2NyaXB0b3IucHJvdG8i/QcKDEphdmFGZWF0dXJlcxL+AQoSbGVnYWN5X2Ns",
            "b3NlZF9lbnVtGAEgASgIQuEBiAEBmAEEmAEBogEJEgR0cnVlGIQHogEKEgVm",
            "YWxzZRjnB7IBuwEI6AcQ6AcasgFUaGUgbGVnYWN5IGNsb3NlZCBlbnVtIGJl",
            "aGF2aW9yIGluIEphdmEgaXMgZGVwcmVjYXRlZCBhbmQgaXMgc2NoZWR1bGVk",
            "IHRvIGJlIHJlbW92ZWQgaW4gZWRpdGlvbiAyMDI1LiAgU2VlIGh0dHA6Ly9w",
            "cm90b2J1Zi5kZXYvcHJvZ3JhbW1pbmctZ3VpZGVzL2VudW0vI2phdmEgZm9y",
            "IG1vcmUgaW5mb3JtYXRpb24uEp8CCg91dGY4X3ZhbGlkYXRpb24YAiABKA4y",
            "Hy5wYi5KYXZhRmVhdHVyZXMuVXRmOFZhbGlkYXRpb25C5AGIAQGYAQSYAQGi",
            "AQwSB0RFRkFVTFQYhAeyAcgBCOgHEOkHGr8BVGhlIEphdmEtc3BlY2lmaWMg",
            "dXRmOCB2YWxpZGF0aW9uIGZlYXR1cmUgaXMgZGVwcmVjYXRlZCBhbmQgaXMg",
            "c2NoZWR1bGVkIHRvIGJlIHJlbW92ZWQgaW4gZWRpdGlvbiAyMDI1LiAgVXRm",
            "OCB2YWxpZGF0aW9uIGJlaGF2aW9yIHNob3VsZCB1c2UgdGhlIGdsb2JhbCBj",
            "cm9zcy1sYW5ndWFnZSB1dGY4X3ZhbGlkYXRpb24gZmVhdHVyZS4SMAoKbGFy",
            "Z2VfZW51bRgDIAEoCEIciAEBmAEGmAEBogEKEgVmYWxzZRiEB7IBAwjpBxJR",
            "Ch91c2Vfb2xkX291dGVyX2NsYXNzbmFtZV9kZWZhdWx0GAQgASgIQiiIAQGY",
            "AQGiAQkSBHRydWUYhAeiAQoSBWZhbHNlGOkHsgEGCOkHIOkHEn8KEm5lc3Rf",
            "aW5fZmlsZV9jbGFzcxgFIAEoDjI3LnBiLkphdmFGZWF0dXJlcy5OZXN0SW5G",
            "aWxlQ2xhc3NGZWF0dXJlLk5lc3RJbkZpbGVDbGFzc0IqiAECmAEDmAEGmAEI",
            "ogELEgZMRUdBQ1kYhAeiAQcSAk5PGOkHsgEDCOkHGnwKFk5lc3RJbkZpbGVD",
            "bGFzc0ZlYXR1cmUiWAoPTmVzdEluRmlsZUNsYXNzEh4KGk5FU1RfSU5fRklM",
            "RV9DTEFTU19VTktOT1dOEAASBgoCTk8QARIHCgNZRVMQAhIUCgZMRUdBQ1kQ",
            "AxoIIgYI6Qcg6QdKCAgBEICAgIACIkYKDlV0ZjhWYWxpZGF0aW9uEhsKF1VU",
            "RjhfVkFMSURBVElPTl9VTktOT1dOEAASCwoHREVGQVVMVBABEgoKBlZFUklG",
            "WRACOjwKBGphdmESGy5nb29nbGUucHJvdG9idWYuRmVhdHVyZVNldBjpByAB",
            "KAsyEC5wYi5KYXZhRmVhdHVyZXNCKAoTY29tLmdvb2dsZS5wcm90b2J1ZkIR",
            "SmF2YUZlYXR1cmVzUHJvdG8="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { JavaFeaturesExtensions.Java }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.JavaFeatures), global::Pb.JavaFeatures.Parser, new[]{ "LegacyClosedEnum", "Utf8Validation", "LargeEnum", "UseOldOuterClassnameDefault", "NestInFileClass" }, null, new[]{ typeof(global::Pb.JavaFeatures.Types.Utf8Validation) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Pb.JavaFeatures.Types.NestInFileClassFeature), global::Pb.JavaFeatures.Types.NestInFileClassFeature.Parser, null, null, new[]{ typeof(global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass) }, null, null)})
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of java_features.proto</summary>
  public static partial class JavaFeaturesExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.JavaFeatures> Java =
      new pb::Extension<global::Google.Protobuf.Reflection.FeatureSet, global::Pb.JavaFeatures>(1001, pb::FieldCodec.ForMessage(8010, global::Pb.JavaFeatures.Parser));
  }

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class JavaFeatures : pb::IMessage<JavaFeatures>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JavaFeatures> _parser = new pb::MessageParser<JavaFeatures>(() => new JavaFeatures());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JavaFeatures> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.JavaFeaturesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JavaFeatures() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JavaFeatures(JavaFeatures other) : this() {
      _hasBits0 = other._hasBits0;
      legacyClosedEnum_ = other.legacyClosedEnum_;
      utf8Validation_ = other.utf8Validation_;
      largeEnum_ = other.largeEnum_;
      useOldOuterClassnameDefault_ = other.useOldOuterClassnameDefault_;
      nestInFileClass_ = other.nestInFileClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JavaFeatures Clone() {
      return new JavaFeatures(this);
    }

    /// <summary>Field number for the "legacy_closed_enum" field.</summary>
    public const int LegacyClosedEnumFieldNumber = 1;
    private readonly static bool LegacyClosedEnumDefaultValue = false;

    private bool legacyClosedEnum_;
    /// <summary>
    /// Whether or not to treat an enum field as closed.  This option is only
    /// applicable to enum fields, and will be removed in the future.  It is
    /// consistent with the legacy behavior of using proto3 enum types for proto2
    /// fields.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LegacyClosedEnum {
      get { if ((_hasBits0 & 1) != 0) { return legacyClosedEnum_; } else { return LegacyClosedEnumDefaultValue; } }
      set {
        _hasBits0 |= 1;
        legacyClosedEnum_ = value;
      }
    }
    /// <summary>Gets whether the "legacy_closed_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLegacyClosedEnum {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "legacy_closed_enum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLegacyClosedEnum() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "utf8_validation" field.</summary>
    public const int Utf8ValidationFieldNumber = 2;
    private readonly static global::Pb.JavaFeatures.Types.Utf8Validation Utf8ValidationDefaultValue = global::Pb.JavaFeatures.Types.Utf8Validation.Unknown;

    private global::Pb.JavaFeatures.Types.Utf8Validation utf8Validation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.JavaFeatures.Types.Utf8Validation Utf8Validation {
      get { if ((_hasBits0 & 2) != 0) { return utf8Validation_; } else { return Utf8ValidationDefaultValue; } }
      set {
        _hasBits0 |= 2;
        utf8Validation_ = value;
      }
    }
    /// <summary>Gets whether the "utf8_validation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUtf8Validation {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "utf8_validation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUtf8Validation() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "large_enum" field.</summary>
    public const int LargeEnumFieldNumber = 3;
    private readonly static bool LargeEnumDefaultValue = false;

    private bool largeEnum_;
    /// <summary>
    /// Allows creation of large Java enums, extending beyond the standard
    /// constant limits imposed by the Java language.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LargeEnum {
      get { if ((_hasBits0 & 4) != 0) { return largeEnum_; } else { return LargeEnumDefaultValue; } }
      set {
        _hasBits0 |= 4;
        largeEnum_ = value;
      }
    }
    /// <summary>Gets whether the "large_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLargeEnum {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "large_enum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLargeEnum() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "use_old_outer_classname_default" field.</summary>
    public const int UseOldOuterClassnameDefaultFieldNumber = 4;
    private readonly static bool UseOldOuterClassnameDefaultDefaultValue = false;

    private bool useOldOuterClassnameDefault_;
    /// <summary>
    /// Whether to use the old default outer class name scheme, or the new feature
    /// which adds a "Proto" suffix to the outer class name.
    ///
    /// Users will not be able to set this option, because we removed it in the
    /// same edition that it was introduced. But we use it to determine which
    /// naming scheme to use for outer class name defaults.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UseOldOuterClassnameDefault {
      get { if ((_hasBits0 & 8) != 0) { return useOldOuterClassnameDefault_; } else { return UseOldOuterClassnameDefaultDefaultValue; } }
      set {
        _hasBits0 |= 8;
        useOldOuterClassnameDefault_ = value;
      }
    }
    /// <summary>Gets whether the "use_old_outer_classname_default" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUseOldOuterClassnameDefault {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "use_old_outer_classname_default" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUseOldOuterClassnameDefault() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "nest_in_file_class" field.</summary>
    public const int NestInFileClassFieldNumber = 5;
    private readonly static global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass NestInFileClassDefaultValue = global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass.Unknown;

    private global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass nestInFileClass_;
    /// <summary>
    /// Whether to nest the generated class in the generated file class. This is
    /// only applicable to *top-level* messages, enums, and services.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass NestInFileClass {
      get { if ((_hasBits0 & 16) != 0) { return nestInFileClass_; } else { return NestInFileClassDefaultValue; } }
      set {
        _hasBits0 |= 16;
        nestInFileClass_ = value;
      }
    }
    /// <summary>Gets whether the "nest_in_file_class" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNestInFileClass {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "nest_in_file_class" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNestInFileClass() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JavaFeatures);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JavaFeatures other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LegacyClosedEnum != other.LegacyClosedEnum) return false;
      if (Utf8Validation != other.Utf8Validation) return false;
      if (LargeEnum != other.LargeEnum) return false;
      if (UseOldOuterClassnameDefault != other.UseOldOuterClassnameDefault) return false;
      if (NestInFileClass != other.NestInFileClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLegacyClosedEnum) hash ^= LegacyClosedEnum.GetHashCode();
      if (HasUtf8Validation) hash ^= Utf8Validation.GetHashCode();
      if (HasLargeEnum) hash ^= LargeEnum.GetHashCode();
      if (HasUseOldOuterClassnameDefault) hash ^= UseOldOuterClassnameDefault.GetHashCode();
      if (HasNestInFileClass) hash ^= NestInFileClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLegacyClosedEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyClosedEnum);
      }
      if (HasUtf8Validation) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Utf8Validation);
      }
      if (HasLargeEnum) {
        output.WriteRawTag(24);
        output.WriteBool(LargeEnum);
      }
      if (HasUseOldOuterClassnameDefault) {
        output.WriteRawTag(32);
        output.WriteBool(UseOldOuterClassnameDefault);
      }
      if (HasNestInFileClass) {
        output.WriteRawTag(40);
        output.WriteEnum((int) NestInFileClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLegacyClosedEnum) {
        output.WriteRawTag(8);
        output.WriteBool(LegacyClosedEnum);
      }
      if (HasUtf8Validation) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Utf8Validation);
      }
      if (HasLargeEnum) {
        output.WriteRawTag(24);
        output.WriteBool(LargeEnum);
      }
      if (HasUseOldOuterClassnameDefault) {
        output.WriteRawTag(32);
        output.WriteBool(UseOldOuterClassnameDefault);
      }
      if (HasNestInFileClass) {
        output.WriteRawTag(40);
        output.WriteEnum((int) NestInFileClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLegacyClosedEnum) {
        size += 1 + 1;
      }
      if (HasUtf8Validation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Utf8Validation);
      }
      if (HasLargeEnum) {
        size += 1 + 1;
      }
      if (HasUseOldOuterClassnameDefault) {
        size += 1 + 1;
      }
      if (HasNestInFileClass) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NestInFileClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JavaFeatures other) {
      if (other == null) {
        return;
      }
      if (other.HasLegacyClosedEnum) {
        LegacyClosedEnum = other.LegacyClosedEnum;
      }
      if (other.HasUtf8Validation) {
        Utf8Validation = other.Utf8Validation;
      }
      if (other.HasLargeEnum) {
        LargeEnum = other.LargeEnum;
      }
      if (other.HasUseOldOuterClassnameDefault) {
        UseOldOuterClassnameDefault = other.UseOldOuterClassnameDefault;
      }
      if (other.HasNestInFileClass) {
        NestInFileClass = other.NestInFileClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LegacyClosedEnum = input.ReadBool();
            break;
          }
          case 16: {
            Utf8Validation = (global::Pb.JavaFeatures.Types.Utf8Validation) input.ReadEnum();
            break;
          }
          case 24: {
            LargeEnum = input.ReadBool();
            break;
          }
          case 32: {
            UseOldOuterClassnameDefault = input.ReadBool();
            break;
          }
          case 40: {
            NestInFileClass = (global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LegacyClosedEnum = input.ReadBool();
            break;
          }
          case 16: {
            Utf8Validation = (global::Pb.JavaFeatures.Types.Utf8Validation) input.ReadEnum();
            break;
          }
          case 24: {
            LargeEnum = input.ReadBool();
            break;
          }
          case 32: {
            UseOldOuterClassnameDefault = input.ReadBool();
            break;
          }
          case 40: {
            NestInFileClass = (global::Pb.JavaFeatures.Types.NestInFileClassFeature.Types.NestInFileClass) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the JavaFeatures message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// The UTF8 validation strategy to use.
      /// </summary>
      public enum Utf8Validation {
        /// <summary>
        /// Invalid default, which should never be used.
        /// </summary>
        [pbr::OriginalName("UTF8_VALIDATION_UNKNOWN")] Unknown = 0,
        /// <summary>
        /// Respect the UTF8 validation behavior specified by the global
        /// utf8_validation feature.
        /// </summary>
        [pbr::OriginalName("DEFAULT")] Default = 1,
        /// <summary>
        /// Verifies UTF8 validity overriding the global utf8_validation
        /// feature. This represents the legacy java_string_check_utf8 option.
        /// </summary>
        [pbr::OriginalName("VERIFY")] Verify = 2,
      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class NestInFileClassFeature : pb::IMessage<NestInFileClassFeature>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<NestInFileClassFeature> _parser = new pb::MessageParser<NestInFileClassFeature>(() => new NestInFileClassFeature());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<NestInFileClassFeature> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Pb.JavaFeatures.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestInFileClassFeature() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestInFileClassFeature(NestInFileClassFeature other) : this() {
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestInFileClassFeature Clone() {
          return new NestInFileClassFeature(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as NestInFileClassFeature);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(NestInFileClassFeature other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(NestInFileClassFeature other) {
          if (other == null) {
            return;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the NestInFileClassFeature message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum NestInFileClass {
            /// <summary>
            /// Invalid default, which should never be used.
            /// </summary>
            [pbr::OriginalName("NEST_IN_FILE_CLASS_UNKNOWN")] Unknown = 0,
            /// <summary>
            /// Do not nest the generated class in the file class.
            /// </summary>
            [pbr::OriginalName("NO")] No = 1,
            /// <summary>
            /// Nest the generated class in the file class.
            /// </summary>
            [pbr::OriginalName("YES")] Yes = 2,
            /// <summary>
            /// Fall back to the `java_multiple_files` option. Users won't be able to
            /// set this option.
            /// </summary>
            [pbr::OriginalName("LEGACY")] Legacy = 3,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
